### ISSUE TITLE
请教下为什么dump、analyse设计成只能调用一次

### ISSUE THREAD

**Issue by zjxckangkang** [KwaiAppTeam/KOOM#133]
![image](https://user-images.githubusercontent.com/12295833/130420700-b69d8dea-5436-45b7-9f60-58c3d2f3a780.png)

**Comment by AndroidInternal** [comment]
触发的阈值已经比较高，后续会有分析大量重复内容

**Comment by Luo1Xiong** [comment]
> 触发的阈值已经比较高，后续会有分析大量重复内容

实际情况是，如果已经dump过了，再次dump会不成功的

**Comment by jiayuliang1314** [comment]
一次运行只能一个，一个版本15个

**Comment by AndroidInternal** [comment]
#175
