### ISSUE TITLE
dump hprof失败

### ISSUE THREAD

**Issue by Luo1Xiong** [KwaiAppTeam/KOOM#151]
在一些6.x设备上总是dump失败

失败时，过滤包名 会得到如下的进程

system    7903  18057 1865800 150048 futex_wait f72a7ba0 S com.yx.demo
system    18057 3837  1861676 327308 SyS_epoll_ f72d11e4 S com.yx.demo
system    25745 3837  1610240 79736 SyS_epoll_ f72d11e4 S com.yx.demo:heap_analysis

总是有一个futex_wait的进程一直在

请问这个futex_wait是干什么的？是主进程在等待子进程fork完成吗？但主进程已经可以响应触摸事件了

**Comment by Luo1Xiong** [comment]
> 在一些6.x设备上总是dump失败
> 
> 失败时，过滤包名 会得到如下的进程
> 
> system 7903 18057 1865800 150048 futex_wait f72a7ba0 S com.yx.demo
> system 18057 3837 1861676 327308 SyS_epoll_ f72d11e4 S com.yx.demo
> system 25745 3837 1610240 79736 SyS_epoll_ f72d11e4 S com.yx.demo:heap_analysis
> 
> 总是有一个futex_wait的进程一直在
> 
> 请问这个futex_wait是干什么的？是主进程在等待子进程fork完成吗？但主进程已经可以响应触摸事件了

而且这个 futex_wait标注的进程 一直都在 不会结束  除非重启机器才行

**Comment by AndroidInternal** [comment]
自带demo能不能复现

**Comment by Luo1Xiong** [comment]
> 自带demo能不能复现

自带demo没出现过这种情况  
有没有可能跟hprof大小有关？

**Comment by alhah** [comment]
futex_wait是android上锁的实现，只是说明当前线程在等锁，没有特别含义，请上传失败的完整日志。
