### ISSUE TITLE
微信群二维码过期了

### ISSUE THREAD

**Issue by NightstarsLi** [KwaiAppTeam/KOOM#160]
请更新一下，谢谢

**Comment by wustor** [comment]
![Screenshot_2021-11-15-23-11-27-507_com.tencent.mm.jpg](https://user-images.githubusercontent.com/13513477/141805709-45de00b3-a892-4bab-9963-34609e7538a1.jpg)

**Comment by lbtrace** [comment]
@wustor @NightstarsLi 二维码已经更新了
