### ISSUE TITLE
arm 32位系统 有什么内存监控工具吗？

### ISSUE THREAD

**Issue by pansaipan** [KwaiAppTeam/KOOM#167]

**Comment by chongbo2013** [comment]
支持 armeabi吗

**Comment by alhah** [comment]
Native内存泄露么?目前不支持的原因是没做32位的fast unwind,且32位的设备占比很低.技术上来讲并不难做到.

**Comment by lbtrace** [comment]
同时，32 位 APK 应用商店即将全面禁止，泄漏问题本身是不区分 CPU ABI 的，所以我们只做了 64 位的监控
