### ISSUE TITLE
一次App生命周期中只触发一次dump和process old hprof是出于什么考虑呢？

### ISSUE THREAD

**Issue by limonzet** [KwaiAppTeam/KOOM#175]
<img width="821" alt="企业微信截图_581b262b-c2d4-4dea-afd1-b084a38a36e7" src="https://user-images.githubusercontent.com/16120493/150083452-15c4efc5-c34f-4a69-9883-dd0676d300b7.png">

**Comment by wzxx** [comment]
同问！！!

**Comment by AndroidInternal** [comment]
1.性能
2.多短时间内多次触发的镜像大部分内容是雷同的

**Comment by wzxx** [comment]
您好，已收到邮件，但现在本人还未登陆邮箱，无法马上回复您的邮件。 我将在登陆邮箱后，尽快给您回复，谢谢~
