### ISSUE TITLE
native 监控，线上偶现崩溃

### ISSUE THREAD

**Issue by xiong0320** [KwaiAppTeam/KOOM#176]
Operating system: Android
                  0.0.0 Linux 4.14.186+ #1 SMP PREEMPT Tue Dec 21 18:11:00 CST 2021 aarch64
KDumpVersion: 1.1
VersionInfo: 13.19.0.d6fd59029c-cn00587
ABIType: arm64-v8a
ProcessName: cn.xxx.xxx
java stack trace: 
	at com.kwai.koom.nativeoom.leakmonitor.LeakMonitor.nativeGetLeakAllocs(Native Method)
	at com.kwai.koom.nativeoom.leakmonitor.LeakMonitor.call(LeakMonitor.kt:5)
	at com.kwai.koom.nativeoom.leakmonitor.LeakMonitor.access$nativeGetLeakAllocs(LeakMonitor.kt:1)
                                                    call
	at com.kwai.koom.base.loop.LoopMonitor$mLoopRunnable$1.run(LoopMonitor.kt:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:264)
	at android.os.HandlerThread.run(HandlerThread.java:67)

CPU: arm64
     8 CPUs

GPU: UNKNOWN

Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x7d65ac0000
Process uptime: not available

Thread 48 (crashed)
 0  libkoom-native.so + 0x610ac
     x0 = 0x0000007d3456eca0    x1 = 0x0000007d65b14b08
     x2 = 0x0000007d454855b8    x3 = 0x0000000000000010
     x4 = 0x0000000000000036    x5 = 0x0000000000000000
     x6 = 0x0000000000001000    x7 = 0x0000000000000000
     x8 = 0x0000007d65ac0000    x9 = 0x0000007d65bc7000
    x10 = 0x0000007d65ac0004   x11 = 0x0000000000000001
    x12 = 0x0000000000000000   x13 = 0x0000000000000000
    x14 = 0x0000000000000000   x15 = 0x0000000000000000
    x16 = 0x0000007e713a9848   x17 = 0x0000007e7139f0bc
    x18 = 0x0000007d26bf0000   x19 = 0x0000007d454855b8
    x20 = 0x0000007d65b14b08   x21 = 0x0000007d3456eca0
    x22 = 0x0000007d44fe1210   x23 = 0x0000007d34569940
    x24 = 0x000000009ed66040   x25 = 0x000000006fd44d08
    x26 = 0x0000000000000001   x27 = 0x0000007d44fe1000
    x28 = 0x0000000000000000    fp = 0x0000007d45485530
     lr = 0x0000007d44f65f18    sp = 0x0000007d45485530
     pc = 0x0000007d44f660ac
    Found by: given as instruction pointer in context
 1  libkoom-native.so + 0x60f14
     fp = 0x0000007d45485610    lr = 0x0000007d44f66ba4
     sp = 0x0000007d45485540    pc = 0x0000007d44f65f18
    Found by: previous frame's frame pointer
 2  libkoom-native.so + 0x61ba0
     fp = 0x0000000000000000    lr = 0x0000007d7b16bdc0
     sp = 0x0000007d45485620    pc = 0x0000007d44f66ba4
    Found by: previous frame's frame pointer

**Comment by lbtrace** [comment]
感谢反馈，麻烦下次遇到问题时，上传下完整的 tombstone 信息 @xiong0320
