### ISSUE TITLE
android12已经出来了，有机会支持吗？

### ISSUE THREAD

**Issue by tianwailaike61** [KwaiAppTeam/KOOM#180]
开源码中是不支持android12 子进程调用Debug.dumpHprofData的，能够支持一下吗？

**Comment by alhah** [comment]
理论上是支持的，还在内部验证稳定性中，目前Android 12的覆盖率较低(1%)，等验证完了会放开版本的限制，如果急用的话可以改版本限制重新打包

**Comment by tianwailaike61** [comment]
> 理论上是支持的，还在内部验证稳定性中，目前Android 12的覆盖率较低(1%)，等验证完了会放开版本的限制，如果急用的话可以改版本限制重新打包

确实可行，感谢回复
