### ISSUE TITLE
native崩溃

### ISSUE THREAD

**Issue by AndroidLi123** [KwaiAppTeam/KOOM#197]
使用demo里的start native leak monitor崩溃了

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Crash time: '2022-8-29 18:53:23'
ro.bootimage.build.date: 'Mon Aug 29 11:23:32 CST 2022'
ro.build.display.id: 'gin-userdebug 8.1.0 OPM1.171019.026 44251 test-keys'
Build fingerprint: 'Android/gin/gin:8.1.0/OPM1.171019.026/44251:userdebug/test-keys'
Revision: '0'
ABI: 'arm64'
pid: 22857, tid: 22980, name: LoopThread  >>> com.kwai.koom.demo <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7376e3aff8
    x0   0000000000000080  x1   0000000000000000  x2   0000007377e10928  x3   0000000000000008
    x4   0000000000000000  x5   0000007376e3b258  x6   b82f651374000000  x7   0000007413652fb8
    x8   6e8d23bbb28c6822  x9   0000000000000001  x10  0000000000000000  x11  0000007377e11000
    x12  0000000000000017  x13  0000000000000000  x14  0000000000000080  x15  0000007376c02090
    x16  00000073749b3138  x17  00000074135e5f98  x18  0000000000000000  x19  00000073749b4a80
    x20  0000000000000080  x21  0000007376f3d588  x22  0000000000000001  x23  0000007374c8d000
    x24  000000000000000e  x25  0000007376f3d588  x26  00000073777b26a0  x27  0000000000000001
    x28  0000000000000001  x29  0000007376e3b050  x30  00000073749a399c
    sp   0000007376e3afd0  pc   000000741365eaac  pstate 0000000080000000
    v0   00000000000019b800000000000019c6  v1   00000000000019b400000000000019c2
    v2   0000007413653238000000741365322c  v3   00000000000000000000000000000000
    v4   00000000000000000000000000000000  v5   00000000000000000000000000000000
    v6   00000000000000000000000000000000  v7   00000000000000000000000000000000
    v8   00000000000000000000000000000000  v9   00000000000000000000000000000000
    v10  00000000000000000000000000000000  v11  00000000000000000000000000000000
    v12  00000000000000000000000000000000  v13  00000000000000000000000000000000
    v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
    v16  00000000000000000000000000000000  v17  00000000000000000000000000000000
    v18  00000000000000000000000000000000  v19  00000000000000000000000042180000
    v20  00000000000000000000000000000000  v21  00000000000000000000000000000000
    v22  00000000000000000000000000000000  v23  fffffffffffffff7fffffffffffffff7
    v24  00000000000002860000000000000286  v25  000000000000022d000000000000022d
    v26  000000000000009f00000000000000ea  v27  00000000000001be000000000000022d
    v28  000000000000009e000000000000009e  v29  000000000000012a0000000000000158
    v30  00000000000001ba0000000000000213  v31  00000000000001ec00000000000001ba
    fpsr 00000011  fpcr 00000000

backtrace:
    #00 pc 0000000000093aac  /system/lib64/libc.so (je_malloc+40)
    #01 pc 000000000001b998  /data/app/com.kwai.koom.demo-Kg0rlRf7G6vAI8HTkQUnyA==/lib/arm64/libkoom-native.so
    #02 pc 00000000000ec6b0  /data/app/com.kwai.koom.demo-Kg0rlRf7G6vAI8HTkQUnyA==/lib/arm64/libc++_shared.so (__emutls_get_address+244)

stack:
         ........  ........
         ........  ........
    #01  0000007376e3b060  0000000000000000
         0000007376e3b068  0000000000000000
         0000007376e3b070  0000000000000000
         0000007376e3b078  6e8d23bbb28c6822
         0000007376e3b080  0000007376e3b120
         0000007376e3b088  0000007374c796b4  /data/app/com.kwai.koom.demo-Kg0rlRf7G6vAI8HTkQUnyA==/lib/arm64/libc++_shared.so (__emutls_get_address+248)
         0000007376e3b090  0000007374c8d000  [anon:.bss]
         0000007376e3b098  6e8d23bbb28c6822
         0000007376e3b0a0  0000000000000001
         0000007376e3b0a8  0000000000000070
         0000007376e3b0b0  0000000000000080
         0000007376e3b0b8  00000073749b4a80  /data/app/com.kwai.koom.demo-Kg0rlRf7G6vAI8HTkQUnyA==/lib/arm64/libkoom-

   
--------- log main
08-29 18:53:20.548 22857 22980 V kwai_dlfcn: android_api_ = 27
08-29 18:53:23.088 22857 22980 I libmemunreachable: unreachable memory detection done
08-29 18:53:23.088 22857 22980 E libmemunreachable: 720 bytes in 10 allocations unreachable out of 10187968 bytes in 21520 allocations

**Comment by lbtrace** [comment]
See #194 , will be fix in v2.2.1

**Comment by lbtrace** [comment]
直接关注 #194 , 先 close 这个问题
