### ISSUE TITLE
监控内存策略

### ISSUE THREAD

**Issue by catdrinker** [KwaiAppTeam/KOOM#20]
关于java堆内存监控策略，想知道为何你们的策略是这样
![image](https://user-images.githubusercontent.com/52711714/90511952-e19da780-e18f-11ea-8b4c-f9c6f8ea293a.png)
理论上不是应该内存越小，阀值百分比预留越大嘛，对于低内存设备应该预留更多内存吧，这里为何是反过来的

**Comment by AndroidInternal** [comment]
避免太容易触发
