### ISSUE TITLE
系统 FD 问题

### ISSUE THREAD

**Issue by liuqingdada** [KwaiAppTeam/KOOM#235]
目前监控线程的创建很有效，能看出是谁创建的，始作俑者被抓到。

但是 FD 的创建没有 Hook，所以只通过FD的link路径，无法定位到创建者。

是否考虑以后增加这一功能。

**Comment by seekting** [comment]
hi,liuqingdada
我们内部已经开发了线程、FD泄露的监控，能把一些创建过多的线程、fd的堆栈聚合找出来；近期会开源上线，敬请期待

**Comment by liuqingdada** [comment]
非常感谢您的回复


&nbsp; &nbsp; FD 的监控功能具体有哪些呢？
&nbsp; &nbsp; 创建者，销毁等等，是否都可以 Hook 到


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KwaiAppTeam/KOOM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月24日(星期五) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KwaiAppTeam/KOOM] 系统 FD 问题 (Issue #235)





 
hi,liuqingdada
 我们内部已经开发了线程、FD泄露的监控，能把一些创建过多的线程、fd的堆栈聚合找出来；近期会开源上线，敬请期待

**Comment by seekting** [comment]
出现fd超阈值时，把当前没关的fd列表报上来，还有每个fd打开的堆栈（本地做完聚合）报上来。

**Comment by liuqingdada** [comment]
谢谢，很期待新功能，给大佬点赞

**Comment by liuqingdada** [comment]
大概什么时间会发布

**Comment by Xinmeng322** [comment]
你的邮件已收到。

**Comment by liuqingdada** [comment]
> 你的邮件已收到。

您好，新版本预计什么时候回发版呢

**Comment by alhah** [comment]
> > 你的邮件已收到。
> 
> 您好，新版本预计什么时候回发版呢

@seekting

**Comment by liuqingdada** [comment]
@seekting 您好，新版本预计什么时候回发版呢

**Comment by liuqingdada** [comment]
发现有新提交，这个问题解决了么

**Comment by seekting** [comment]
@Xinmeng322  感谢您的关注，由于内部的事情较多，这个Q没排上，预计会在下个Q 7~9月份上线吧

**Comment by liuqingdada** [comment]
@seekting 感谢您的解答，持续关注

**Comment by liuqingdada** [comment]
@seekting @Xinmeng322  您好，这个功能可以预览了么

**Comment by Xinmeng322** [comment]
你的邮件已收到。

**Comment by liuqingdada** [comment]
@seekting @Xinmeng322 @alhah 您好，这个问题，预计什么时候发版呢
