### ISSUE TITLE
native leak模块live_alloc_records_无限增大问题

### ISSUE THREAD

**Issue by Mr-JingShi** [KwaiAppTeam/KOOM#245]
### 问题描述
```
struct Test
{
    Test() {
        ptr = new int[100];
    }
    ~Test() {
        delete[] ptr;
    }
    int* ptr;
    int a[100];
};

Test* test = new Test;
// delete test;
```
如上代码所示，new Test时会有两次new运算符被调用，RegisterAlloc会被调用两次，GetLeakAllocs时只检测到了test，并没有检测到test.ptr。因此test.ptr永远被留在了live_alloc_records_里，live_alloc_records_有无限增大的问题。

### std::string也有此现象
https://github.com/KwaiAppTeam/KOOM/blob/a5430e2db995fb67435936bb2bddf1b42f690578/koom-demo/src/main/jni/native-leak-test.cpp#L69
在OnMonitor和RegisterAlloc新增部分打印
```
I/KOOM: OnMonitor address:0x7e9485e460 size:24
I/KOOM: RegisterAlloc address:0x7e9485e460 size:24
I/NativeLeakTest: TestNewLeak 0x7e9485e460 size 16
```
但只要稍微将string的长度变大点，例如：
```
auto str_ptr = new std::string("test_leak_string -- test_leak_string");
```
也会复现此现象，如下所示，可以清晰的看到两次内存申请
```
I/KOOM: OnMonitor address:0x7e86bc5980 size:24
I/KOOM: RegisterAlloc address:0x7e86bc5980 size:24
I/KOOM: OnMonitor address:0x7e86cab910 size:48
I/KOOM: RegisterAlloc address:0x7e86cab910 size:48
I/NativeLeakTest: TestNewLeak 0x7e86bc5980 size 36
```
stl里的其他容器也很令人担忧（目前仅针对std::string进行了测试）。

### 佐证
将get_unreachable_fn_的结果unreachable_memory进行打印
```
I/KOOM: unreachable_memory:  160 bytes in 4 unreachable allocations
      ABI: 'arm64'
    
      32 bytes unreachable at 7e86bc5980
       referencing 48 unreachable bytes in 1 allocation
```
rreferencing 48 unreachable bytes in 1 allocation就是描述的此现象。

### 解决思路
目前我能想到的是通过改造libmemunreachable源码解决此问题。
老师，看看是否有好的办法解决此问题？

**Comment by Mr-JingShi** [comment]
今天想到一个简单方法：将泄漏的地方进行UnregisterAlloc并free操作，可解决此问题。
https://github.com/KwaiAppTeam/KOOM/blob/a5430e2db995fb67435936bb2bddf1b42f690578/koom-native-leak/src/main/jni/src/leak_monitor.cpp#L209
修改为
```
freeMonitor(reinterpret_cast<void*>(CONFUSE(live->address)));
```

**Comment by zqhGeek** [comment]
直接释放掉内存并不好吧，是否leak的判断也不一定准确，作为工具直接释放掉用户的内存，等用户使用的时候会野指针或者直接crash，我觉得宁愿释放掉自身的记录堆栈也比直接释放用户内存要好。

**Comment by Mr-JingShi** [comment]
> 直接释放掉内存并不好吧，是否leak的判断也不一定准确，作为工具直接释放掉用户的内存，等用户使用的时候会野指针或者直接crash，我觉得宁愿释放掉自身的记录堆栈也比直接释放用户内存要好。

（1）内存泄漏检测并能保证100%正确，线上检测出来的仍需要人工确认。
（2）检测工具不该擅自动用户空间的内存。
感谢🙏

**Comment by Xinmeng322** [comment]
你的邮件已收到。
