### ISSUE TITLE
leakcanary替换fast dump，release编译不过

### ISSUE THREAD

**Issue by clunyes** [KwaiAppTeam/KOOM#246]
现在项目中debugImplementation leakcanary，替换了fast dump 后
```
DefaultInitTask.init(applicationContext as Application)
    LeakCanary.config = LeakCanary.config.copy(
      heapDumper = HeapDumper {
        ForkJvmHeapDumper.getInstance().dump(it.absolutePath)
      })
```
release 编译不过，这咋处理

**Comment by alhah** [comment]
编译失败的日志帮忙发下

**Comment by clunyes** [comment]
> 

就是我的leakcanary是debugImplementation依赖的，release没有

**Comment by clunyes** [comment]
现在不想leakcanary侵入release包。但是debug包想换个heapDumper，因为老是dump的时候，应用直接闪退。

**Comment by alhah** [comment]
debugImplementation fast-dump可以么？

**Comment by clunyes** [comment]
> debugImplementation fast-dump可以么？
、、、
DefaultInitTask.init(applicationContext as Application)
    LeakCanary.config = LeakCanary.config.copy(
      heapDumper = HeapDumper {
        ForkJvmHeapDumper.getInstance().dump(it.absolutePath)
      })
、、、
那这段代码，release还是编译不了

**Comment by alhah** [comment]
你把这段代码放到一个子库里，然后debugImplementation，或者放到单独文件里，用gradle指定debug版编译
