### ISSUE TITLE
koom-thread不支持Android 12

### ISSUE THREAD

**Issue by EdminhPeng** [KwaiAppTeam/KOOM#250]
目前市场Android 12系统已比较普遍，koom-thread何时可以支持Android 12及以上设备？

**Comment by Xinmeng322** [comment]
你的邮件已收到。

**Comment by zefengsysu** [comment]
https://github.com/KwaiAppTeam/KOOM/releases/tag/v2.2.2 2.2.2 版本已经发布，koom-thread 支持已经放开到 Android 34（Android 14）
