### ISSUE TITLE
实测相对低端的机器上，Koom report 几乎不会回调

### ISSUE THREAD

**Issue by CatJason** [KwaiAppTeam/KOOM#265]
实测相对低端的机器上，Koom shark 几乎跑不下来，暂时不知道是不是手机性能不行还是有bug，红米K50是可以跑完分析的，拿到上报的 json文件的，现在 Koom fork 进程不支持 12 以上，12以下 shark 分析 hprof 不知道是性能不够还是线程挂掉了（暂时还没来得及深究），很是尴尬，不能开箱即用

**Comment by Xinmeng322** [comment]
你的邮件已收到。
