### ISSUE TITLE
OPPO、VIVO KUtils.getSpaceInGB崩溃 statvfs failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by 496260178** [KwaiAppTeam/KOOM#28]
OPPO、VIVO出现大量目录异常崩溃，使用自定义路径同样崩溃

默认路径：java.lang.IllegalArgumentException:Invalid path: /data/data/xxx/cache/koom
自定义路径：java.lang.IllegalArgumentException:Invalid path: /storage/emulated/0/Android/data/xxx/files/oom

statvfs failed: ENOENT (No such file or directory)
com.kwai.koom.javaoom.common.KUtils.float getSpaceInGB(java.lang.String)(SourceFile:1)

1 java.lang.IllegalArgumentException:Invalid path: /storage/emulated/0/Android/data/xxx/files/oom
--
2 android.os.StatFs.doStat(StatFs.java:53)
3 ......
4 android.system.ErrnoException:statvfs failed: ENOENT (No such file or directory)
5 libcore.io.Linux.statvfs(Native Method)
6 libcore.io.ForwardingOs.statvfs(ForwardingOs.java:224)
7 libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:396)
8 libcore.io.ForwardingOs.statvfs(ForwardingOs.java:224)
9 android.system.Os.statvfs(Os.java:660)
10 android.os.StatFs.doStat(StatFs.java:51)
11 android.os.StatFs.<init>(StatFs.java:43)
12 com.kwai.koom.javaoom.common.KUtils.float getSpaceInGB(java.lang.String)(SourceFile:1)
13 com.kwai.koom.javaoom.KOOMEnableChecker.boolean isSpaceEnough()(SourceFile:2)
14 com.kwai.koom.javaoom.KOOMEnableChecker.com.kwai.koom.javaoom.KOOMEnableChecker$Result doCheck()(SourceFile:5)
15 com.kwai.koom.javaoom.KOOMInternal.void startInternal()(SourceFile:6)
16 com.kwai.koom.javaoom.KOOMInternal.void lambda$4g_V3sFLeyJdaTqLAVnSM2d0x_4(com.kwai.koom.javaoom.KOOMInternal)(Unknown Source:0)
17 com.kwai.koom.javaoom.-$$Lambda$KOOMInternal$4g_V3sFLeyJdaTqLAVnSM2d0x_4.run(Unknown Source:2)
18 android.os.Handler.handleCallback(Handler.java:883)
19 android.os.Handler.dispatchMessage(Handler.java:100)
20 android.os.Looper.loop(Looper.java:238)
21 android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by AndroidInternal** [comment]
有没有可以复现的demo或者操作路径

**Comment by 496260178** [comment]
未复现，线上公测用户崩溃，有观察到用户可用存储很低



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 李锐 <notifications@github.com&gt;
发送时间: 2020年9月25日 09:59
收件人: KwaiAppTeam/KOOM <KOOM@noreply.github.com&gt;
抄送: 496260178 <496260178@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[KwaiAppTeam/KOOM] OPPO、VIVO KUtils.getSpaceInGB崩溃 statvfs failed: ENOENT (No such file or directory) (#28)

**Comment by AndroidInternal** [comment]
#29 加了try-catch

```gradle
dependencies {
    implementation 'com.kwai.koom:java-oom:1.0.7'
}
```
