### ISSUE TITLE
NullPointerException Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference

### ISSUE THREAD

**Issue by 496260178** [KwaiAppTeam/KOOM#30]
1 java.lang.RuntimeException:Unable to create application booter.ReleaseApp: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
--
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4986)
3 ......
4 java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
5 com.kwai.koom.javaoom.common.KConfig$KConfigBuilder.void <init>()(SourceFile:6)
6 com.kwai.koom.javaoom.common.KConfig.com.kwai.koom.javaoom.common.KConfig defaultConfig()(SourceFile:1)
7 com.kwai.koom.javaoom.KOOMInternal.void buildConfig(android.app.Application)(SourceFile:2)
8 com.kwai.koom.javaoom.KOOMInternal.void <init>(android.app.Application)(SourceFile:3)
9 com.kwai.koom.javaoom.KOOM.void <init>(android.app.Application)(SourceFile:3)
10 com.kwai.koom.javaoom.KOOM.void init(android.app.Application)(SourceFile:6)
12 booter.App.void onCreate()(SourceFile:21)
13 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1022)
14 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4983)
15 android.app.ActivityThread.-wrap1(ActivityThread.java)
16 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
17 android.os.Handler.dispatchMessage(Handler.java:111)
18 android.os.Looper.loop(Looper.java:207)
19 android.app.ActivityThread.main(ActivityThread.java:5778)
20 java.lang.reflect.Method.invoke(Native Method)
21 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
22 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)

**Comment by AndroidInternal** [comment]
init传参application为空，检查init调用时机

**Comment by 496260178** [comment]
传参application不应该会为空，bugly都已经正常初始化并捕获到异常
```
@Override
public void onCreate() {
        super.onCreate();
        xxx.initBugly(this);
        xxx.initOOMMonitor(this);
    }

public static void initOOMMonitor(final Application application) {
        KOOM.init(application);
        KOOM.getInstance().setRootDir(StorageManager.getOomFileDir());
        KOOM.getInstance().setProgressListener(progress -> AppLogger.d("OOMMonitor", "progress state " + progress.toString()));
        KOOM.getInstance().setHeapReportUploader(file -> {
            // Upload the report or do something else.
            // File is deleted automatically when callback is done by default.
        });

        File reportDir = new File(KOOM.getInstance().getReportDir());
        File[] listFiles = reportDir.listFiles();
        if (listFiles != null && listFiles.length > 0) {
            for (File report : listFiles) {
                // Upload the report or do something else.
            }
        }
    }
```

**Comment by AndroidInternal** [comment]
崩在了这里getCacheDir()返回了空
```java
this.rootDir = KGlobalConfig.getApplication().getCacheDir()
          .getAbsolutePath() + File.separator + KOOM_DIR;
```

如果是在Application的onCreate里init，不应该有这个问题

**Comment by AndroidInternal** [comment]
或者和sdcard被拔了之类的情况有关，能否复现？

**Comment by 496260178** [comment]
不能复现，只发现一次异常，以后再次使用观察看看
