### ISSUE TITLE
关于ForkJvmHeapDumper的疑问

### ISSUE THREAD

**Issue by Caij** [KwaiAppTeam/KOOM#33]
我看到ForkJvmHeapDumper中主要是三步
trySuspendVMThenFork();
resumeVM()
waitDumping
fork进程后，并没有发现子进程dump相关的api调用，有点不太理解。子进程会自动dump吗？

然后可以更新一下群二维码吗

**Comment by AndroidInternal** [comment]
https://github.com/KwaiAppTeam/KOOM/blob/3e865fc0233dc6dd624e1a4df02335e1d19498e0/java-oom/src/main/java/com/kwai/koom/javaoom/dump/ForkJvmHeapDumper.java#L65-L75

`Debug.dumpHprofData(path); `调用虚拟机API执行dump。

`fork`返回0时，进入子进程执行代码。

**Comment by Caij** [comment]
![image](https://user-images.githubusercontent.com/8597839/95597212-eccece80-0a80-11eb-82b2-10c0da0e64cd.png)
的确比较难理解这个文章的内容，我尝试把代码改为下面图里面的  发现工作正常, 能dump出文件。

![image](https://user-images.githubusercontent.com/8597839/95597309-0708ac80-0a81-11eb-8007-2117ef6dda02.png)

**Comment by AndroidInternal** [comment]
只fork的话，理论上应该会因为suspend失败，打印报错日志，参考这里：

https://android.googlesource.com/platform/art/+/master/runtime/thread_list.cc#671

具体报错为`Timed out waiting for threads to suspend, waited for`

demo能正常工作是每次都正常？如果每次都正常，确实比较奇怪，原因可能是因为demo太简单了，多申请一些线程再试试看

**Comment by Caij** [comment]
尝试创建多个线程会触发异常，刚才去补了一下知识
子进程只保留父进程执行fork操作的当前线程。其他线程等不到返回结果，导致超时。

非常感谢

**Comment by AndroidInternal** [comment]
群二维码已更新
