### ISSUE TITLE
请问KOOM有自动监控并分析的功能吗？

### ISSUE THREAD

**Issue by TokyoAndroid** [KwaiAppTeam/KOOM#34]
Demo里面是在`KOOM.manualTrigger()`中主动去抓取hprof文件并分析然后生成报告的，那么，如果我不主动去调用此函数，看逻辑应该是在内存超过阈值3次之后去抓取的，对吗？
另外，还有一个疑问，App在打开过程中，只能抓取一次数据吗？当我尝试重复调用`KOOM.manualTrigger()`时，好像并不起作用啊。
望解答，谢谢！

**Comment by Tinaom** [comment]
同问

**Comment by TokyoAndroid** [comment]
刚刚测试了一下，自动监测的内存算法是否存在问题呀！（手机华为Mate8）
项目中算法是用`Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()`，表示用掉的内存，然后用这个值去除以`Runtime.getRuntime().maxMemory()`，表示用掉的内存占总内存的百分比，若高于80（或其他自定义的值），则表示内存超标。

实际测试如下：
当前我将内存增加后的内存情况：
`Runtime.getRuntime().maxMemory() 402 653 184  
Runtime.getRuntime().totalMemory() : 33 517 790  
Runtime.getRuntime().freeMemory() : 919 662`

根据算法测试值：
`HeapMonitor: 占用比8.095833（结果已经乘以100了）   阈值：85.0`
那么，如果是自动监测的话，我的手机永远不可能触发内存分析了 。。。。

**Comment by AndroidInternal** [comment]
_在内存超过阈值3次之后去抓取的，对吗？_

对的。

_App在打开过程中，只能抓取一次数据吗？_

是的。

_如果是自动监测的话，我的手机永远不可能触发内存分析_

没理解你的问题。宗旨就是会在濒临OOM时触发，查找出有问题的内存占用，8%的内存占用很正常不会触发分析。

**Comment by TokyoAndroid** [comment]
> _Q:在内存超过阈值3次之后去抓取的，对吗？_
> 
> A:对的。
> 
> _Q:App在打开过程中，只能抓取一次数据吗？_
> 
> A:是的。
> 
> _Q:如果是自动监测的话，我的手机永远不可能触发内存分析_
> 
> A:没理解你的问题。宗旨就是会在濒临OOM时触发，查找出有问题的内存占用，8%的内存占用很正常不会触发分析。

如果是自动监测的话，我的手机永远不可能触发内存分析——这个可以忽略了，是我自己计算错了，我把freeMemory当成了App剩余可用内存。现在已经弄清楚了，谢谢大佬解答！
