### ISSUE TITLE
关于bitmap泄漏判定规则的疑问

### ISSUE THREAD

**Issue by YouJZ** [KwaiAppTeam/KOOM#37]
我看到源码的规则是当bitmap的大小超过DEFAULT_BIG_BITMAP时，就判断该bitmap发生了泄漏，这个不一定吧。如果当前页面展示了一个超过DEFAULT_BIG_BITMAP大小的图片时，这个图片会判断为泄漏么？还是说这里只是把当前的大图片给过滤出来，是否为泄漏还得另外判断？ @AndroidInternal

**Comment by AndroidInternal** [comment]
会。bitmap大图报出来，需要主动去看是否有问题。

**Comment by YouJZ** [comment]
嗯嗯 感谢回复。
