### ISSUE TITLE
分析hprof的时候出现问题

### ISSUE THREAD

**Issue by liminwanqing** [KwaiAppTeam/KOOM#39]
10-27 20:58:29.309 11841 11868 I HeapAnalyzer: analyze
10-27 20:58:29.309 11841 11868 I LeaksFinder: build index file:/data/user/0/com.kwai.koom.demo/cache/koom/hprof/2020-10-27_20-58-28.hprof
10-27 20:58:29.742 11841 11868 W System.err: java.lang.IllegalStateException: Unknown tag 0x88 at 3379433 after 0x23 at 3379369
10-27 20:58:29.743 11841 11868 W System.err:    at kshark.HprofReader.readHprofRecords(HprofReader.kt:446)
10-27 20:58:29.743 11841 11868 W System.err:    at kshark.internal.HprofInMemoryIndex$Companion.createReadingHprof(HprofInMemoryIndex.kt:377)
10-27 20:58:29.743 11841 11868 W System.err:    at kshark.HprofHeapGraph$Companion.indexHprof(HprofHeapGraph.kt:244)
10-27 20:58:29.743 11841 11868 W System.err:    at com.kwai.koom.javaoom.analysis.SuspicionLeaksFinder.buildIndex(SuspicionLeaksFinder.java:205)
10-27 20:58:29.743 11841 11868 W System.err:    at com.kwai.koom.javaoom.analysis.SuspicionLeaksFinder.find(SuspicionLeaksFinder.java:88)
10-27 20:58:29.744 11841 11868 W System.err:    at com.kwai.koom.javaoom.analysis.KHeapAnalyzer.analyze(KHeapAnalyzer.java:44)
10-27 20:58:29.744 11841 11868 W System.err:    at com.kwai.koom.javaoom.analysis.HeapAnalyzeService.doAnalyze(HeapAnalyzeService.java:113)
10-27 20:58:29.744 11841 11868 W System.err:    at com.kwai.koom.javaoom.analysis.HeapAnalyzeService.onHandleIntent(HeapAnalyzeService.java:85)
10-27 20:58:29.744 11841 11868 W System.err:    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
10-27 20:58:29.744 11841 11868 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
10-27 20:58:29.745 11841 11868 W System.err:    at android.os.Looper.loop(Looper.java:223)
10-27 20:58:29.745 11841 11868 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by AndroidInternal** [comment]
应该是hprof不完整。

是必现的吗？什么机型和版本？

**Comment by liminwanqing** [comment]
> 应该是hprof不完整。
> 
> 是必现的吗？什么机型和版本？

不是必现，meizu 16t，我多试几次看看
