### ISSUE TITLE
koom文件夹中没有任何report 文件

### ISSUE THREAD

**Issue by Tinaom** [KwaiAppTeam/KOOM#40]
按照文档说明接入KOOM 后，测试好久，发现koom文件夹中没有任何文件，手动调用KOOM.getInstance().manualTrigger() 也没解决，请问是什么问题，
com.kwai.koom:java-oom:1.0.7

**Comment by AndroidInternal** [comment]
手动调用不该没有，提供一下设备信息，运行日志

**Comment by waesteve** [comment]
可以切换下设备，结合logcat输出，分析一下。 比如ROM不足5G，就会直接失败。查看下hprof文件是否生成，确定是dump的问题还是anaysis的问题
