### ISSUE TITLE
trySuspendVMThenFork 什么场景会返回 0 呢？

### ISSUE THREAD

**Issue by aWangami** [KwaiAppTeam/KOOM#41]
```Java
    try {
      int pid = trySuspendVMThenFork();
      if (pid == 0) {
        Debug.dumpHprofData(path);
        KLog.i(TAG, "notifyDumped:" + dumpRes);
        //System.exit(0);
        exitProcess();
      } else {
        resumeVM();
        dumpRes = waitDumping(pid);
        KLog.i(TAG, "hprof pid:" + pid + " dumped: " + path);
      }

    } catch (IOException e) {
      e.printStackTrace();
      KLog.e(TAG, "dump failed caused by IOException!");
    }
```

trySuspendVMThenFork 什么场景会返回 0 呢？fork 返回值是不是只有在子进程下进行才会返回0，但是我们 KOOM 都是运行在主进程的呀？这一点不太理解，还望解答😁 @AndroidInternal

**Comment by AndroidInternal** [comment]
搜索实践一下fork的用法。不太准确的描述，你可以认为fork会返回2次，一次在主进程一次在子进程，等于0时代表当前在子进程。

**Comment by aWangami** [comment]
![image](https://user-images.githubusercontent.com/17882528/100560355-83d13d80-32f0-11eb-9b99-ef0dff56c352.png)

多加了一条日志把 Pid 打印出来，只有 Pid = 11615，没有 Pid = 0。是不是要特殊场景才会触发？

**Comment by AndroidInternal** [comment]
不需要特殊场景。有两点确认下：

1.fork进程是单线程的，子进程只有当前线程一个线程存活，logcat应该会失效、logcat日志是无法在控制台显示的

2.fork返回的两次会在两个不同的进程，所以即使能够查看logcat日志，也需要展示所有进程的日志

**Comment by aWangami** [comment]
是的，确实是 🤦‍♂️ 我在 Logcat 里面被过滤掉了

![image](https://user-images.githubusercontent.com/17882528/100834491-f2f09280-34a6-11eb-870a-b835f398b769.png)

**Comment by aWangami** [comment]
是我对 fork 这一块的理解还不够，3Q
