### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by stylsw** [KwaiAppTeam/KOOM#43]
@Override
    public void run() {
      if (stop) {
        return;
      }

      if (KConstants.Debug.VERBOSE_LOG) {
        Log.i(TAG, monitor.monitorType() + " monitor run");
      }

      if (monitor.isTrigger()) {
        Log.i(TAG, monitor.monitorType() + " monitor "
            + monitor.monitorType() + " trigger");
        stop = monitorTriggerListener
            .onTrigger(monitor.monitorType(), monitor.getTriggerReason());
      }

      if (!stop) {
        handler.postDelayed(this, monitor.pollInterval());
      }
    }

java.lang.NullPointerException
Attempt to invoke interface method 'boolean com.kwai.koom.javaoom.monitor.MonitorTriggerListener.onTrigger(com.kwai.koom.javaoom.monitor.MonitorType, com.kwai.koom.javaoom.monitor.TriggerReason)' on a null object reference

**Comment by AndroidInternal** [comment]
这个默认是不会为空的，有自定义MonitorTriggerListener吗
