### ISSUE TITLE
有个疑问啊

### ISSUE THREAD

**Issue by shijiannihao** [KwaiAppTeam/KOOM#44]
![image](https://user-images.githubusercontent.com/14315776/102059963-8c675f00-3e2c-11eb-9c03-9417375f38f9.png)
fork dump和strip dump是不是只能选择一种 ，没有fork dump 和strip dump 一起使用？

**Comment by AndroidInternal** [comment]
可以一起使用。现有的代码目前还不支持，需要改一下。
