### ISSUE TITLE
想把KOOM接入到我们项目线上监控

### ISSUE THREAD

**Issue by impeiwei** [KwaiAppTeam/KOOM#57]
想把KOOM接入到我们项目线上监控, 想了解快手那边在线上监控指标有哪些、采集hprof性能、以及线上采集策略等一些情况。（二维码过期）

还有比如, 触发时机：
出现OOM -> hprof 
泄露 -> hprof
LowMemory -> hprof

**Comment by Yis92** [comment]
兄弟现在接入了么，留个联系方式一起交流下

**Comment by Yis92** [comment]
兄弟现在接入了么，留个联系方式一起交流下
