### ISSUE TITLE
Thread starting during runtime shutdown  com.kwai.koom.javaoom.common.KVData.void init()(SourceFile:2)

### ISSUE THREAD

**Issue by stylsw** [KwaiAppTeam/KOOM#61]
1 java.lang.Thread.nativeCreate(Native Method)
--
2 java.lang.Thread.start(Thread.java:1063)
3 android.app.SharedPreferencesImpl.startLoadFromDisk(SharedPreferencesImpl.java:88)
4 android.app.SharedPreferencesImpl.<init>(SharedPreferencesImpl.java:81)
5 android.app.ContextImpl.getSharedPreferences(ContextImpl.java:358)
6 android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:171)
7 com.kwai.koom.javaoom.common.KVData.void init()(SourceFile:2)
8 com.kwai.koom.javaoom.common.KVData.long firstLaunchTime(java.lang.String)(SourceFile:2)
9 com.kwai.koom.javaoom.KOOMEnableChecker.boolean isDateExpired()(SourceFile:2)
10 com.kwai.koom.javaoom.KOOMEnableChecker.com.kwai.koom.javaoom.KOOMEnableChecker$Result doCheck()(SourceFile:7)
11 com.kwai.koom.javaoom.KOOMInternal.void startInternal()(SourceFile:6)
12 com.kwai.koom.javaoom.-$$Lambda$0djp1uDEn8XhoKOAxawfvgrwyEU.run(lambda)
13 android.os.Handler.handleCallback(Handler.java:739)
14 android.os.Handler.dispatchMessage(Handler.java:95)
15 android.os.Looper.loop(Looper.java:148)
16 android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by AndroidInternal** [comment]
Thread starting during runtime shutdown 

是个例吧。初始化时机有问题，或者是个别设备极端问题

**Comment by stylsw** [comment]
已经解决了，其他原因导致的，多谢回复
发送自 Windows 10 版邮件应用

发件人: 李锐
发送时间: 2021年3月10日 17:45
收件人: KwaiAppTeam/KOOM
抄送: Sweet; Author
主题: Re: [KwaiAppTeam/KOOM] Thread starting during runtime shutdown com.kwai.koom.javaoom.common.KVData.void init()(SourceFile:2) (#61)

Thread starting during runtime shutdown
是个例吧。初始化时机有问题，或者是个别设备极端问题
