### ISSUE TITLE
为什么在dump之前没有去触发gc，这样数据不是更准确吗？

### ISSUE THREAD

**Issue by Lapisy** [KwaiAppTeam/KOOM#62]
为什么在dump之前没有去触发gc，这样数据不是更准确吗？是否是因为COW机制的原因（因为gc会写内存）。这样理解是否准确？

**Comment by AndroidInternal** [comment]
主要是GC会导致页面明显卡顿，其次是无法覆盖大量临时内存被迅速分配的情况。
