### ISSUE TITLE
dump进程出现了SIGSEGV(SEGV_ACCERR)

### ISSUE THREAD

**Issue by liuling07** [KwaiAppTeam/KOOM#65]
你好，我们在使用KOOM的时候，ret = ForkJvmHeapDumper().dump(hprofPath)，调用这句代码dump内存快照的时候，在Android 10系统上面出现比较多的SIGSEGV(SEGV_ACCERR)crash上报。看日志，出现的进程都是dump进程，不影响主进程。内存快照也正常dump了，就是上报了这个crash。帮看下什么原因？
`Build fingerprint: HONOR/JSN-AL00/HWJSN-H:10/HONORJSN-AL00/10.0.0.168C00:user/release-keys
Revision: 0
ABI: arm64
time: 2021-03-12 03:00:17
pid: 25770, tid: 25770, name: main  >>> com.xxx.xxxx <<<
signal: 11 (SIGSEGV), code: 2 (SEGV_ACCERR) fault addr: 0x1513c830
si_errno:0, si_errnoMsg:Success, sending pid:0, sending uid:0
    r0: 0x000000007091fac8  r1: 0x000000001446b090  r2: 0x000000001513c828
    r3: 0x000000007080fdb0  r4: 0x0000000000000e0a  r5: 0x0000000000000030
    r6: 0x0000000000000f60  r7: 0x0000000000000010  r8: 0x0000000000000018
    r9: 0x000000009d4db9b0  r10: 0x00000079f7b13691  r11: 0x0000007a65546448
    r12: 0x0000007a6554649c  r13: 0x0000007a655464f0  r14: 0x0000007a65546550
    r15: 0x000000001434aee8  r16: 0x0000000000000000  r17: 0x00000000000511ac
    r18: 0x000000793c13a000  r19: 0x00000078fba95000  r20: 0x0000000000000000
    r21: 0x000000001513c828  r22: 0x000000001446b090  r23: 0x000000001513c828
    r24: 0x000000001446afb0  r25: 0x000000798f921020  r26: 0x00000078fba950b0
    r27: 0x0000000000000002  r28: 0x000000000000000a  r29: 0x000000798f91e770
    r30: 0x000000009d4d58b0  sp: 0x000000798f91e650  pc: 0x0000000071de7d1c
    pstate: 0x0000000080000000
        #00    pc 00000000002f8d1c    /system/framework/arm64/boot.oat [arm64-v8a::24b2f2282cb8494eaee96585e10f68d8]
        #01    pc 000000009d4d58ac    <unknown>`

**Comment by alhah** [comment]
可能是dump快照以后dump进程没有立刻退出，更新最新版本看看

**Comment by alhah** [comment]
请用2.0版本
