### ISSUE TITLE
1.0.7

### ISSUE THREAD

**Issue by FlyqiangHigh** [KwaiAppTeam/KOOM#69]
当前载入的1.0.7是没有适配android N的，啥时候更新一个版本吧。

**Comment by alhah** [comment]
没有适配Android N指的是dlopen么，kwai-linker已经适配到Android 11了

**Comment by FlyqiangHigh** [comment]
通过gradle 的方式 implementation 'com.kwai.koom:java-oom:1.0.7'的代码还没有更新，当前线上clone下来的我看是已经适配了的。

**Comment by alhah** [comment]
release的版本适配到了Android 10，没适配11，N都适配了

**Comment by FlyqiangHigh** [comment]
刚才说错了，是android R的，是的，不知道后续有没有计划适配R的计划。

**Comment by alhah** [comment]
R已经在master分支适配了，不过内部讨论还有优化的空间，计划等完善以后再正式发布，目前建议先用开关控制，R不开

**Comment by FlyqiangHigh** [comment]
手动鼓掌，期待正式发布
