### ISSUE TITLE
StripHprofHeapDumper裁剪后的镜像shark解析出现异常（必现）

### ISSUE THREAD

**Issue by wanggaohui** [KwaiAppTeam/KOOM#73]
![image](https://user-images.githubusercontent.com/40512643/114645339-d80f1400-9d0b-11eb-8c71-9b405fdc57d5.png)

**Comment by wanggaohui** [comment]
![image](https://user-images.githubusercontent.com/40512643/114989272-d8eda480-9ec9-11eb-921f-0eb5f3ff2f3b.png)

把HPROF_PRIMITIVE_ARRAY_DUMP中app space的裁剪去掉就可以正常分析了，应该是这部分裁剪的问题

**Comment by AndroidInternal** [comment]
裁剪的镜像需要回填数组，后面把回填数组的工具更新上来

**Comment by chongbo2013** [comment]
@AndroidInternal 是不是只要回填字节0

**Comment by AndroidInternal** [comment]
2.0版本更新了回填数组工具，详细查看文档
