### ISSUE TITLE
Android 11 系统上dumpHprofDataNative  SEGV_MAPERR

### ISSUE THREAD

**Issue by JavanHuang123** [KwaiAppTeam/KOOM#79]
你好，我们线上灰度时发现部分11系统会出现SEGV_MAPERR崩溃
机型分别是“三星 SM G9960“，“VIVO V2046A”，“OPPO PDSM00”
1 #00 pc 002183b8 /apex/com.android.art/lib/libart.so (art::hprof::Hprof::LookupStackTraceSerialNumber(art::mirror::Object const*)+131) [armeabi-v8]
--
2 #01 pc 00217037 /apex/com.android.art/lib/libart.so (art::hprof::Hprof::DumpHeapClass(art::mirror::Class*)+506) [armeabi-v8]
3 #02 pc 00216cd5 /apex/com.android.art/lib/libart.so (art::hprof::Hprof::DumpHeapObject(art::mirror::Object*)+3580) [armeabi-v8]
4 #03 pc 00220e57 /apex/com.android.art/lib/libart.so (void art::gc::accounting::SpaceBitmap<8u>::VisitMarkedRange<art::hprof::Hprof::ProcessBody()::'lambda'(art::mirror::Object*)&>(unsigned int, unsigned int, art::hprof::Hprof::ProcessBody()::'lambda'(art::mirror::Object*)&&&) const+162) [armeabi-v8]
5 #04 pc 002202a9 /apex/com.android.art/lib/libart.so (art::hprof::Hprof::ProcessBody()+772) [armeabi-v8]
6 #05 pc 0021f993 /apex/com.android.art/lib/libart.so (art::hprof::Hprof::ProcessHeap(bool)+96) [armeabi-v8]
7 #06 pc 0021bfa1 /apex/com.android.art/lib/libart.so (art::hprof::Hprof::Dump()+2748) [armeabi-v8]
8 #07 pc 00001c5f /data/app/~~Pr6JRjustA8GOlUXS1Aq0g==/-JrmwWRkmm6IEBSdXRyPgCA==/lib/arm/KOOM.so (Java_com_kwai_koom_javaoom_dump_ForkJvmHeapDumper_dumpHprofDataNative+174) [armeabi-v7a]
9 #08 pc 0040d1f5 /data/app/~~Pr6JRjustA8GOlUXS1Aq0g==/-JrmwWRkmm6IEBSdXRyPgCA==/oat/arm/base.odex [armeabi]

**Comment by zhuxianfeng13** [comment]
+1

**Comment by zhuxianfeng13** [comment]
我也出现这个问题了，我看最新的版本已经把Android11disable了，线上Android11还是先别打开koom吧

**Comment by alhah** [comment]
Android 11要开的话可以下载master分支的代码自己编译，还没有正式release
