### ISSUE TITLE
android 7.1 dump时link虚拟机函数存在异常

### ISSUE THREAD

**Issue by wanggaohui** [KwaiAppTeam/KOOM#87]
![image](https://user-images.githubusercontent.com/40512643/120738459-75bfdc00-c522-11eb-88a6-f08a5cb93026.png)

导致在fork的子进程中偶现dump hprof失败，程序停在Debug.dumpHprofData处不往后走（子进程不退出）。

**Comment by AndroidInternal** [comment]
已知问题，下个版本修复
