### ISSUE TITLE
想请教一个问题，Fragment判定泄漏嫌疑规则中mCalled属性为啥要为true才行

### ISSUE THREAD

**Issue by wanggaohui** [KwaiAppTeam/KOOM#91]
![image](https://user-images.githubusercontent.com/40512643/123916647-79754000-d9b4-11eb-8a12-2a28069ce298.png)

这个是AS上profiler分析出的泄漏嫌疑对象，其中ProductEmptyFragment的mCalled属性为false但仍判定存在泄漏的嫌疑，这个和koom的判定规则有一定出入。

**Comment by AndroidInternal** [comment]
规避只是创建了一个新的fragment还没有使用的case
