### ISSUE TITLE
Android 5.1上报了Crash日志  # MonitorThread(108)  SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by lvhx1996** [KwaiAppTeam/KOOM#92]
Android 5.1.1 大量出现，Android 10目前只出现了一次。
#00 pc 001157b0 /system/lib/libart.so (art::Dbg::SuspendVM()+20)
#01 pc 000013dd /data/app/com.xingjiabi.shengsheng-1/lib/arm/libkoom-java.so (Java_com_kwai_koom_javaoom_dump_ForkJvmHeapDumper_trySuspendVMThenFork+20) [armeabi-v7a::02cefe22259849d110a6c71723e97d86]
java:
com.kwai.koom.javaoom.dump.ForkJvmHeapDumper.dump(SourceFile:8)
com.kwai.koom.javaoom.dump.HeapDumpTrigger.a(SourceFile:7)
com.kwai.koom.javaoom.dump.HeapDumpTrigger.a(SourceFile:19)
com.kwai.koom.javaoom.dump.HeapDumpTrigger.a(SourceFile:2)
com.kwai.koom.javaoom.dump.a.a(lambda)
com.kwai.koom.javaoom.monitor.MonitorThread$MonitorRunnable.run(SourceFile:9)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:135)
android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by alhah** [comment]
还能复现么？用2.0试一下，这里崩溃要么是本身有内存越界，要么是获取SuspendVM符号的时候拿错了
