### ISSUE TITLE
请教一个问题，关于android11兼容性问题

### ISSUE THREAD

**Issue by atheJack** [KwaiAppTeam/KOOM#93]
koom是不支持android11吗，但是为什么demo工程在android11手机上也能跑出来，而且生成了报告。但是我自己新建一个项目，导入依赖并初始化，在log里会发现android11手机会提示操作系统不兼容

**Comment by MRwangqi** [comment]
@atheJack  查看一下你的 dump 是不是使用的 ForkJvmHeapDumper，对于 Android 11 我看是有适配的
```
  // Compatible with Android 11
    if (Build.VERSION.SDK_INT > Build.VERSION_CODES.Q) {
      return dumpHprofDataNative(path);
    }
```

**Comment by atheJack** [comment]
最新版的依赖版本号就是这个1.1.0吗

**Comment by atheJack** [comment]
demo工程里面对于版本号的判断是>=5.0&&<=11 但是这个1.1.0版本sdk里面是>=5.0&&<=11呢

**Comment by atheJack** [comment]
/**
   * Versions below Android 5.0 and above android 10.0 are incompatible now.
   *
   * @return support
   */
  public boolean isVersionPermit() {
    return Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP
        && Build.VERSION.SDK_INT < Build.VERSION_CODES.R;
  }

**Comment by alhah** [comment]
Android 11上还不稳定，属于实验功能
