### ISSUE TITLE
有个疑惑想了解一下

### ISSUE THREAD

**Issue by MRwangqi** [KwaiAppTeam/KOOM#94]
摘自《快手客户端稳定性体系建设》
> dump 前需要暂停所有java线程，而子进程只保留父进程执行 fork 操作的线程，在子进程中执行 SuspendAll 触发暂停是永远等不到其他线程返回结果的(详见thread_list.cc中行SuspendAll的实现，这里不展开讲了)

永远等不到其他线程返回结果这句话不太明白，我所理解的是，子进程去 dump ，暂停也只是子进程的所有线程，dump 结束后就结束了，为啥要父进程去先 suspendAll

**Comment by alhah** [comment]
子进程里只有一个线程(主进程执行fork操作的线程)，没有其他线程，而线程列表是从主进程中继承过来的，暂停的时候会发现其他线程都没有暂停，一直等待。

可看下我在qcon上的分享，讲的详细一些
`链接: https://pan.baidu.com/s/1Y4NsPqCEDx9CJMKyT-rZiA  密码: fo1w`

**Comment by MRwangqi** [comment]
@alhah 感谢回复，视频讲授的分享非常 nice，但我还有一个疑问，就是 koom 应用到线上，用的是混淆包，dump 出来的 hprof 解析是没有行号的，那快手这边是怎么将混淆后的泄漏引用链根据 mapping 文件进行恢复呢
