### ISSUE TITLE
app占用内存到达内存阈值时用ForkJvmHeapDumper导出来的内存镜像有200多M，这时用shark解析会报OOM

### ISSUE THREAD

**Issue by Andyload** [KwaiAppTeam/KOOM#95]
![OOM](https://user-images.githubusercontent.com/16317769/125019247-39474900-e0a9-11eb-9846-58292a4b3e00.png)

这个是不是只能考虑用StripHprofHeapDumper来dump了？

**Comment by AndroidInternal** [comment]
升级最新版再试下
