### ISSUE TITLE
A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction

### ISSUE THREAD

**Issue by iostyle** [KwaiAppTeam/KOOM#97]
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 3 files found with path 'lib/x86/libc++_shared.so' from inputs:
      - /Users/x/.gradle/caches/transforms-3/cfa4b953bf704d177dc10c48372043aa/transformed/jetified-mmkv-1.2.7/jni
      - /Users/x/.gradle/caches/transforms-3/dce1b1abbc0753a97e3599a078324b0f/transformed/jetified-java-oom-1.1.0/jni
      - /Users/x/.gradle/caches/transforms-3/ddf3229c156fdc14f04b44e754cf6df4/transformed/jetified-kwai-linker-1.1.0/jni

**Comment by zjxckangkang** [comment]
在gradle配置下这个
android{
//...
 packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
//...
}

**Comment by iostyle** [comment]
> 在gradle配置下这个
> android{
> //...
> packagingOptions {
> pickFirst 'lib/arm64-v8a/libc++_shared.so'
> pickFirst 'lib/x86/libc++_shared.so'
> pickFirst 'lib/x86_64/libc++_shared.so'
> pickFirst 'lib/armeabi-v7a/libc++_shared.so'
> }
> //...
> }

可以兄弟
